[package]
name = "roblox-integrations/freeway"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
private = true

[dependencies]
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
Cryo = "uglypoe/cryo@1.0.3"
CreateSharedToolbar = "stravant/create-shared-toolbar@0.1.0"
base64 = "reselim/base64@3.0.0"
studiocomponents = "freeway-rbx/studiocomponents@1.3.0"
GoodSignal = "stravant/goodsignal@0.3.0"